[package]
name = "inherit-config"
description = "Inherit configuration from parent struct"
version = "0.2.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true
homepage.workspace = true

[dependencies]
inherit-config-derive = { path = "../derive", version = "0.2.3" }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }

[lints]
workspace = true
